name: "SwiftLocation CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - macos: macOS-latest
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run:
          swift package generate-xcodeproj
          xcodebuild test -project SwiftLocation.xcodeproj -scheme SwiftLocation -sdk iphonesimulator17.0 -destination "OS=17.0,name=iPhone 15"
