name: "SwiftLocation CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  ios-latest:
    name: Unit Tests (iOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          chmod +X Scripts/test.sh
          Scripts/test.sh -s "SwiftLocation" -d "OS=16.4,name=iPhone 14 Pro"
  macos-latest:
    name: Unit Tests (macOS, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test.sh -d "platform=macOS"
  tvos-latest:
    name: Unit Tests (tvOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          chmod +X Scripts/test.sh
          Scripts/test.sh -s "SwiftLocation" -d "OS=16.4,name=Apple TV"
  watchos-latest:
    name: Run Build (watchOS 9.2, Xcode 14.2)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          chmod +X Scripts/test.sh
          Scripts/build.sh -s "SwiftLocation" -d "OS=9.2,name=Apple Watch Series 8 (45mm)"
  swift-build:
    name: Swift Build (SPM)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
