name: "SwiftLocation CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  ios-latest:
    name: Unit Tests (iOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          Scripts/test.sh -s "SwiftLocation" -d "OS=16.4,name=iPhone 14 Pro"
 # macos-latest:
 #   name: Unit Tests (macOS, Xcode 14.3.1)
 #   runs-on: macOS-13
 #   env:
 #     DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
 #   steps:
 #     - uses: actions/checkout@v2
 #     - name: Run Tests
 #       run: Scripts/test.sh -d "platform=macOS"
  tvos-latest:
    name: Unit Tests (tvOS 16.4, Xcode 14.3.1)
    runs-on: macOS-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          Scripts/test.sh -s "SwiftLocation" -d "OS=16.4,name=Apple TV"
